spring:
  main:
    banner-mode: "off"
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
  datasource:
    url: jdbc:h2:mem:mockup;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

logging.level:
  com.adeliosys: debug
